### ISSUE TITLE
phip command seems broken on current master

### ISSUE THREAD

**Issue by timodonnell** [lasersonlab/phip-stat#15]
```
(py35) tim@tim-digits:~/sinai/git/phip-stat$ python -V
Python 3.5.5
```

```
(py35) tim@tim-digits:~/sinai/git/phip-stat$ pip install -e .
Obtaining file:///home/tim/sinai/git/phip-stat
Collecting click (from phip-stat==0.4.0.dev0)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Requirement already satisfied: tqdm in /home/tim/anaconda3/envs/py35/lib/python3.5/site-packages (from phip-stat==0.4.0.dev0) (4.28.1)
Requirement already satisfied: numpy in /home/tim/anaconda3/envs/py35/lib/python3.5/site-packages (from phip-stat==0.4.0.dev0) (1.15.4)
Requirement already satisfied: scipy in /home/tim/anaconda3/envs/py35/lib/python3.5/site-packages (from phip-stat==0.4.0.dev0) (1.2.0)
Requirement already satisfied: pandas in /home/tim/anaconda3/envs/py35/lib/python3.5/site-packages (from phip-stat==0.4.0.dev0) (0.23.4)
Requirement already satisfied: python-dateutil>=2.5.0 in /home/tim/anaconda3/envs/py35/lib/python3.5/site-packages (from pandas->phip-stat==0.4.0.dev0) (2.7.5)
Requirement already satisfied: pytz>=2011k in /home/tim/anaconda3/envs/py35/lib/python3.5/site-packages (from pandas->phip-stat==0.4.0.dev0) (2018.7)
Requirement already satisfied: six>=1.5 in /home/tim/anaconda3/envs/py35/lib/python3.5/site-packages (from python-dateutil>=2.5.0->pandas->phip-stat==0.4.0.dev0) (1.12.0)
Installing collected packages: click, phip-stat
  Running setup.py develop for phip-stat
Successfully installed click-7.0 phip-stat
```

```
(py35) tim@tim-digits:~/sinai/git/phip-stat$ phip
Traceback (most recent call last):
  File "/home/tim/anaconda3/envs/py35/bin/phip", line 11, in <module>
    load_entry_point('phip-stat', 'console_scripts', 'phip')()
  File "/home/tim/anaconda3/envs/py35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/tim/anaconda3/envs/py35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/home/tim/anaconda3/envs/py35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/home/tim/anaconda3/envs/py35/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/tim/sinai/git/phip-stat/phip/cli.py", line 75
    print(f">{n}\n{s[:length]}", file=op)
                              ^
SyntaxError: invalid syntax
```

**Comment by timodonnell** [comment]
Looks like f-strings are introduced in python 3.6, so it's more a question of what versions of python we want to support

**Comment by laserson** [comment]
Made it clear we're on py36+ in the README
