### ISSUE TITLE
Hit calling syntax bug

### ISSUE THREAD

**Issue by bkellman** [lasersonlab/phip-stat#24]
I believe there is an issue with the hitcalling function. I am running the nature protocols example data through the bowtie2-gampois-factorization snakefile and getting a simple argument count error (below). I checked my pandas version and it is up to date. I'm not sure what else would be causing this issue. Any thoughts on how to resolve?

```
[Tue Aug 29 22:42:20 2023]
rule call_hits:
    input: matrix-residuals.tsv
    output: called-hits.tsv
    jobid: 12
    reason: Missing output files: called-hits.tsv
    resources: tmpdir=/tmp

/usr/bin/bash: /home/bkellman/miniconda3/lib/libtinfo.so.6: no version information available (required by /usr/bin/bash)
Read input matrix: 5001 clones x 3 samples.
Columns: beadsreads_sample1 beadsreads_sample2 _background_0
Ignoring 1 columns matching regex '^_background.*': _background_0
Ignoring 1 rows matching regex '^_background.*': _background_0
Beads-only regex '.*beads.*' matched 2 samples: beadsreads_sample1 beadsreads_sample2
Did NOT normalize counts to reads-per-million.
/home/bkellman/miniconda3/lib/python3.11/site-packages/phip/hit_calling.py:311: RuntimeWarning: invalid value encountered in scalar divide
  return num_false_hits / num_hits
*** Iteration     0 ***
  Pseudocount       : 0.0044
  Hit threshold     : 5.0815 (=10**0.7060)
Traceback (most recent call last):
  File "/home/bkellman/miniconda3/bin/phip", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/bkellman/miniconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bkellman/miniconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/bkellman/miniconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bkellman/miniconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bkellman/miniconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bkellman/miniconda3/lib/python3.11/site-packages/phip/cli.py", line 432, in call_hits
    result_df = do_hit_calling(
                ^^^^^^^^^^^^^^^
  File "/home/bkellman/miniconda3/lib/python3.11/site-packages/phip/hit_calling.py", line 171, in do_hit_calling
    result = minimize_scalar(
             ^^^^^^^^^^^^^^^^
  File "/home/bkellman/miniconda3/lib/python3.11/site-packages/scipy/optimize/_minimize.py", line 935, in minimize_scalar
    res = _minimize_scalar_bounded(fun, bounds, args, **options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bkellman/miniconda3/lib/python3.11/site-packages/scipy/optimize/_optimize.py", line 2285, in _minimize_scalar_bounded
    fx = func(x, *args)
         ^^^^^^^^^^^^^^
  File "/home/bkellman/miniconda3/lib/python3.11/site-packages/phip/hit_calling.py", line 167, in function_to_minimize
    print_summary(current_info)
  File "/home/bkellman/miniconda3/lib/python3.11/site-packages/phip/hit_calling.py", line 146, in print_summary
    % (binary_hits_df.any(1).sum(), binary_hits_df.any(1).mean() * 100.0)
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: NDFrame._add_numeric_operations.<locals>.any() takes 1 positional argument but 2 were given
[Tue Aug 29 22:42:22 2023]
Error in rule call_hits:
    jobid: 12
    input: matrix-residuals.tsv
    output: called-hits.tsv
    shell:
        phip call-hits -i matrix-residuals.tsv -o called-hits.tsv
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-08-29T224217.446701.snakemake.log
```

**Comment by laserson** [comment]
Hi @bkellman, this package is no longer being maintained. I'd recommend you check out phip-flow or BEER, as linked from the main README in the repo.
